// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZQc4M4H0vgAfyZWZFoOM7h-zzH9C9XLE',
    appId: '1:344737353064:web:a4462ba9b6208b3f571add',
    messagingSenderId: '344737353064',
    projectId: 'first1-app01-flutr01',
    authDomain: 'first1-app01-flutr01.firebaseapp.com',
    storageBucket: 'first1-app01-flutr01.appspot.com',
    measurementId: 'G-QG8HP3WL65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYRIedYOfIReIRdkONMqn6gARWFSetnd4',
    appId: '1:344737353064:android:b2a7d35e70b77b58571add',
    messagingSenderId: '344737353064',
    projectId: 'first1-app01-flutr01',
    storageBucket: 'first1-app01-flutr01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcqkdQwfGNQcHajTkp88FhF401UoHGSRg',
    appId: '1:344737353064:ios:f40078691fdce5b6571add',
    messagingSenderId: '344737353064',
    projectId: 'first1-app01-flutr01',
    storageBucket: 'first1-app01-flutr01.appspot.com',
    iosClientId: '344737353064-2vmddt5ubno8ubqi6hgb5ufp2tanau9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcqkdQwfGNQcHajTkp88FhF401UoHGSRg',
    appId: '1:344737353064:ios:f40078691fdce5b6571add',
    messagingSenderId: '344737353064',
    projectId: 'first1-app01-flutr01',
    storageBucket: 'first1-app01-flutr01.appspot.com',
    iosClientId: '344737353064-2vmddt5ubno8ubqi6hgb5ufp2tanau9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
